"""test

Revision ID: 08088b5bc461
Revises: 2d4ed261dad6
Create Date: 2020-09-13 13:59:06.490216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08088b5bc461'
down_revision = '2d4ed261dad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('test', sa.String(length=240), nullable=True))
    op.create_index(op.f('ix_school_test'), 'school', ['test'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_test'), table_name='school')
    op.drop_column('school', 'test')
    # ### end Alembic commands ###
