"""initial

Revision ID: 2d4ed261dad6
Revises: 
Create Date: 2020-09-13 02:02:47.986431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d4ed261dad6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('telephone', sa.Integer(), nullable=True),
    sa.Column('webpage', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('code_number', sa.Integer(), nullable=True),
    sa.Column('number_pupils', sa.Integer(), nullable=True),
    sa.Column('religious', sa.Boolean(), nullable=True),
    sa.Column('religion', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('subregion', sa.String(length=32), nullable=True),
    sa.Column('postcode', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('location_description', sa.String(length=500), nullable=True),
    sa.Column('headteacher', sa.String(length=64), nullable=True),
    sa.Column('headteacher_title', sa.String(length=32), nullable=True),
    sa.Column('director_message', sa.String(length=1000), nullable=True),
    sa.Column('infantil_primer_ciclo', sa.Boolean(), nullable=True),
    sa.Column('infantil', sa.Boolean(), nullable=True),
    sa.Column('primaria', sa.Boolean(), nullable=True),
    sa.Column('secundaria', sa.Boolean(), nullable=True),
    sa.Column('bachillerato', sa.Boolean(), nullable=True),
    sa.Column('formación_profesional', sa.Boolean(), nullable=True),
    sa.Column('description_infantil_primer_ciclo', sa.String(length=1000), nullable=True),
    sa.Column('description_infantil', sa.String(length=1000), nullable=True),
    sa.Column('description_primaria', sa.String(length=1000), nullable=True),
    sa.Column('description_secundaria', sa.String(length=1000), nullable=True),
    sa.Column('description_bachillerato', sa.String(length=1000), nullable=True),
    sa.Column('description_formación_profesional', sa.String(length=1000), nullable=True),
    sa.Column('infantil_primer_ciclo_type', sa.String(length=32), nullable=True),
    sa.Column('infantil_type', sa.String(length=32), nullable=True),
    sa.Column('primaria_type', sa.String(length=32), nullable=True),
    sa.Column('secundaria_type', sa.String(length=32), nullable=True),
    sa.Column('bachillerato_type', sa.String(length=32), nullable=True),
    sa.Column('formación_profesional_type', sa.String(length=32), nullable=True),
    sa.Column('trilingual', sa.Boolean(), nullable=True),
    sa.Column('bilingual', sa.Boolean(), nullable=True),
    sa.Column('first_language', sa.String(length=32), nullable=True),
    sa.Column('second_language', sa.String(length=32), nullable=True),
    sa.Column('third_language', sa.String(length=32), nullable=True),
    sa.Column('fourth_language', sa.String(length=32), nullable=True),
    sa.Column('optionality_first_language', sa.String(length=32), nullable=True),
    sa.Column('optionality_second_language', sa.String(length=32), nullable=True),
    sa.Column('optionality_third_language', sa.String(length=32), nullable=True),
    sa.Column('optionality_fourth_language', sa.String(length=32), nullable=True),
    sa.Column('description_first_language', sa.String(length=1000), nullable=True),
    sa.Column('description_second_language', sa.String(length=1000), nullable=True),
    sa.Column('description_third_language', sa.String(length=1000), nullable=True),
    sa.Column('description_fourth_language', sa.String(length=1000), nullable=True),
    sa.Column('patio_separado_infantil', sa.Boolean(), nullable=True),
    sa.Column('library', sa.Boolean(), nullable=True),
    sa.Column('vegetable_garden', sa.Boolean(), nullable=True),
    sa.Column('facilities_information', sa.String(length=1000), nullable=True),
    sa.Column('sports_facilities', sa.String(length=240), nullable=True),
    sa.Column('canteen', sa.Boolean(), nullable=True),
    sa.Column('in_house_kitchen', sa.Boolean(), nullable=True),
    sa.Column('canteen_price', sa.Integer(), nullable=True),
    sa.Column('horario_ampliado', sa.Boolean(), nullable=True),
    sa.Column('horario_ampliado_morning', sa.String(length=32), nullable=True),
    sa.Column('horario_ampliado_afternoon', sa.String(length=32), nullable=True),
    sa.Column('horario_ampliado_price', sa.Integer(), nullable=True),
    sa.Column('extracurricular_activities', sa.Boolean(), nullable=True),
    sa.Column('extracurricular_activities_list', sa.String(length=500), nullable=True),
    sa.Column('extracurricular_activities_price_from', sa.Integer(), nullable=True),
    sa.Column('extracurricular_activities_price_upto', sa.Integer(), nullable=True),
    sa.Column('nurse', sa.Boolean(), nullable=True),
    sa.Column('nurse_price', sa.Integer(), nullable=True),
    sa.Column('school_bus', sa.Boolean(), nullable=True),
    sa.Column('school_bus_price', sa.Integer(), nullable=True),
    sa.Column('bulletpoint_presentation', sa.String(length=500), nullable=True),
    sa.Column('bulletpoint_methods_and_priorities', sa.String(length=500), nullable=True),
    sa.Column('bulletpoint_specialities', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_address'), 'school', ['address'], unique=False)
    op.create_index(op.f('ix_school_bachillerato'), 'school', ['bachillerato'], unique=False)
    op.create_index(op.f('ix_school_bachillerato_type'), 'school', ['bachillerato_type'], unique=False)
    op.create_index(op.f('ix_school_bilingual'), 'school', ['bilingual'], unique=False)
    op.create_index(op.f('ix_school_bulletpoint_methods_and_priorities'), 'school', ['bulletpoint_methods_and_priorities'], unique=False)
    op.create_index(op.f('ix_school_bulletpoint_presentation'), 'school', ['bulletpoint_presentation'], unique=False)
    op.create_index(op.f('ix_school_bulletpoint_specialities'), 'school', ['bulletpoint_specialities'], unique=False)
    op.create_index(op.f('ix_school_canteen'), 'school', ['canteen'], unique=False)
    op.create_index(op.f('ix_school_canteen_price'), 'school', ['canteen_price'], unique=False)
    op.create_index(op.f('ix_school_city'), 'school', ['city'], unique=False)
    op.create_index(op.f('ix_school_code_number'), 'school', ['code_number'], unique=True)
    op.create_index(op.f('ix_school_description_bachillerato'), 'school', ['description_bachillerato'], unique=False)
    op.create_index(op.f('ix_school_description_first_language'), 'school', ['description_first_language'], unique=False)
    op.create_index(op.f('ix_school_description_formación_profesional'), 'school', ['description_formación_profesional'], unique=False)
    op.create_index(op.f('ix_school_description_fourth_language'), 'school', ['description_fourth_language'], unique=False)
    op.create_index(op.f('ix_school_description_infantil'), 'school', ['description_infantil'], unique=False)
    op.create_index(op.f('ix_school_description_infantil_primer_ciclo'), 'school', ['description_infantil_primer_ciclo'], unique=False)
    op.create_index(op.f('ix_school_description_primaria'), 'school', ['description_primaria'], unique=False)
    op.create_index(op.f('ix_school_description_second_language'), 'school', ['description_second_language'], unique=False)
    op.create_index(op.f('ix_school_description_secundaria'), 'school', ['description_secundaria'], unique=False)
    op.create_index(op.f('ix_school_description_third_language'), 'school', ['description_third_language'], unique=False)
    op.create_index(op.f('ix_school_director_message'), 'school', ['director_message'], unique=False)
    op.create_index(op.f('ix_school_email'), 'school', ['email'], unique=True)
    op.create_index(op.f('ix_school_extracurricular_activities'), 'school', ['extracurricular_activities'], unique=False)
    op.create_index(op.f('ix_school_extracurricular_activities_list'), 'school', ['extracurricular_activities_list'], unique=False)
    op.create_index(op.f('ix_school_extracurricular_activities_price_from'), 'school', ['extracurricular_activities_price_from'], unique=False)
    op.create_index(op.f('ix_school_extracurricular_activities_price_upto'), 'school', ['extracurricular_activities_price_upto'], unique=False)
    op.create_index(op.f('ix_school_facilities_information'), 'school', ['facilities_information'], unique=False)
    op.create_index(op.f('ix_school_first_language'), 'school', ['first_language'], unique=False)
    op.create_index(op.f('ix_school_formación_profesional'), 'school', ['formación_profesional'], unique=False)
    op.create_index(op.f('ix_school_formación_profesional_type'), 'school', ['formación_profesional_type'], unique=False)
    op.create_index(op.f('ix_school_fourth_language'), 'school', ['fourth_language'], unique=False)
    op.create_index(op.f('ix_school_headteacher'), 'school', ['headteacher'], unique=False)
    op.create_index(op.f('ix_school_headteacher_title'), 'school', ['headteacher_title'], unique=False)
    op.create_index(op.f('ix_school_horario_ampliado'), 'school', ['horario_ampliado'], unique=False)
    op.create_index(op.f('ix_school_horario_ampliado_afternoon'), 'school', ['horario_ampliado_afternoon'], unique=False)
    op.create_index(op.f('ix_school_horario_ampliado_morning'), 'school', ['horario_ampliado_morning'], unique=False)
    op.create_index(op.f('ix_school_horario_ampliado_price'), 'school', ['horario_ampliado_price'], unique=False)
    op.create_index(op.f('ix_school_in_house_kitchen'), 'school', ['in_house_kitchen'], unique=False)
    op.create_index(op.f('ix_school_infantil'), 'school', ['infantil'], unique=False)
    op.create_index(op.f('ix_school_infantil_primer_ciclo'), 'school', ['infantil_primer_ciclo'], unique=False)
    op.create_index(op.f('ix_school_infantil_primer_ciclo_type'), 'school', ['infantil_primer_ciclo_type'], unique=False)
    op.create_index(op.f('ix_school_infantil_type'), 'school', ['infantil_type'], unique=False)
    op.create_index(op.f('ix_school_lat'), 'school', ['lat'], unique=False)
    op.create_index(op.f('ix_school_library'), 'school', ['library'], unique=False)
    op.create_index(op.f('ix_school_lng'), 'school', ['lng'], unique=False)
    op.create_index(op.f('ix_school_location_description'), 'school', ['location_description'], unique=False)
    op.create_index(op.f('ix_school_name'), 'school', ['name'], unique=True)
    op.create_index(op.f('ix_school_number_pupils'), 'school', ['number_pupils'], unique=False)
    op.create_index(op.f('ix_school_nurse'), 'school', ['nurse'], unique=False)
    op.create_index(op.f('ix_school_nurse_price'), 'school', ['nurse_price'], unique=False)
    op.create_index(op.f('ix_school_optionality_first_language'), 'school', ['optionality_first_language'], unique=False)
    op.create_index(op.f('ix_school_optionality_fourth_language'), 'school', ['optionality_fourth_language'], unique=False)
    op.create_index(op.f('ix_school_optionality_second_language'), 'school', ['optionality_second_language'], unique=False)
    op.create_index(op.f('ix_school_optionality_third_language'), 'school', ['optionality_third_language'], unique=False)
    op.create_index(op.f('ix_school_patio_separado_infantil'), 'school', ['patio_separado_infantil'], unique=False)
    op.create_index(op.f('ix_school_postcode'), 'school', ['postcode'], unique=False)
    op.create_index(op.f('ix_school_primaria'), 'school', ['primaria'], unique=False)
    op.create_index(op.f('ix_school_primaria_type'), 'school', ['primaria_type'], unique=False)
    op.create_index(op.f('ix_school_region'), 'school', ['region'], unique=False)
    op.create_index(op.f('ix_school_religion'), 'school', ['religion'], unique=False)
    op.create_index(op.f('ix_school_religious'), 'school', ['religious'], unique=False)
    op.create_index(op.f('ix_school_school_bus'), 'school', ['school_bus'], unique=False)
    op.create_index(op.f('ix_school_school_bus_price'), 'school', ['school_bus_price'], unique=False)
    op.create_index(op.f('ix_school_second_language'), 'school', ['second_language'], unique=False)
    op.create_index(op.f('ix_school_secundaria'), 'school', ['secundaria'], unique=False)
    op.create_index(op.f('ix_school_secundaria_type'), 'school', ['secundaria_type'], unique=False)
    op.create_index(op.f('ix_school_sports_facilities'), 'school', ['sports_facilities'], unique=False)
    op.create_index(op.f('ix_school_subregion'), 'school', ['subregion'], unique=False)
    op.create_index(op.f('ix_school_telephone'), 'school', ['telephone'], unique=True)
    op.create_index(op.f('ix_school_third_language'), 'school', ['third_language'], unique=False)
    op.create_index(op.f('ix_school_trilingual'), 'school', ['trilingual'], unique=False)
    op.create_index(op.f('ix_school_vegetable_garden'), 'school', ['vegetable_garden'], unique=False)
    op.create_index(op.f('ix_school_webpage'), 'school', ['webpage'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('opinion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_general', sa.Integer(), nullable=True),
    sa.Column('score_teachers', sa.Integer(), nullable=True),
    sa.Column('score_faculties_materials', sa.Integer(), nullable=True),
    sa.Column('score_communication_accessibility', sa.Integer(), nullable=True),
    sa.Column('opinion_general', sa.String(length=1000), nullable=True),
    sa.Column('opinion_teachers', sa.String(length=1000), nullable=True),
    sa.Column('opinion_faculties_materials', sa.String(length=1000), nullable=True),
    sa.Column('opinion_communication_accessibility', sa.String(length=1000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opinion_opinion_communication_accessibility'), 'opinion', ['opinion_communication_accessibility'], unique=False)
    op.create_index(op.f('ix_opinion_opinion_faculties_materials'), 'opinion', ['opinion_faculties_materials'], unique=False)
    op.create_index(op.f('ix_opinion_opinion_general'), 'opinion', ['opinion_general'], unique=False)
    op.create_index(op.f('ix_opinion_opinion_teachers'), 'opinion', ['opinion_teachers'], unique=False)
    op.create_index(op.f('ix_opinion_score_communication_accessibility'), 'opinion', ['score_communication_accessibility'], unique=False)
    op.create_index(op.f('ix_opinion_score_faculties_materials'), 'opinion', ['score_faculties_materials'], unique=False)
    op.create_index(op.f('ix_opinion_score_general'), 'opinion', ['score_general'], unique=False)
    op.create_index(op.f('ix_opinion_score_teachers'), 'opinion', ['score_teachers'], unique=False)
    op.create_index(op.f('ix_opinion_timestamp'), 'opinion', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opinion_timestamp'), table_name='opinion')
    op.drop_index(op.f('ix_opinion_score_teachers'), table_name='opinion')
    op.drop_index(op.f('ix_opinion_score_general'), table_name='opinion')
    op.drop_index(op.f('ix_opinion_score_faculties_materials'), table_name='opinion')
    op.drop_index(op.f('ix_opinion_score_communication_accessibility'), table_name='opinion')
    op.drop_index(op.f('ix_opinion_opinion_teachers'), table_name='opinion')
    op.drop_index(op.f('ix_opinion_opinion_general'), table_name='opinion')
    op.drop_index(op.f('ix_opinion_opinion_faculties_materials'), table_name='opinion')
    op.drop_index(op.f('ix_opinion_opinion_communication_accessibility'), table_name='opinion')
    op.drop_table('opinion')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_school_webpage'), table_name='school')
    op.drop_index(op.f('ix_school_vegetable_garden'), table_name='school')
    op.drop_index(op.f('ix_school_trilingual'), table_name='school')
    op.drop_index(op.f('ix_school_third_language'), table_name='school')
    op.drop_index(op.f('ix_school_telephone'), table_name='school')
    op.drop_index(op.f('ix_school_subregion'), table_name='school')
    op.drop_index(op.f('ix_school_sports_facilities'), table_name='school')
    op.drop_index(op.f('ix_school_secundaria_type'), table_name='school')
    op.drop_index(op.f('ix_school_secundaria'), table_name='school')
    op.drop_index(op.f('ix_school_second_language'), table_name='school')
    op.drop_index(op.f('ix_school_school_bus_price'), table_name='school')
    op.drop_index(op.f('ix_school_school_bus'), table_name='school')
    op.drop_index(op.f('ix_school_religious'), table_name='school')
    op.drop_index(op.f('ix_school_religion'), table_name='school')
    op.drop_index(op.f('ix_school_region'), table_name='school')
    op.drop_index(op.f('ix_school_primaria_type'), table_name='school')
    op.drop_index(op.f('ix_school_primaria'), table_name='school')
    op.drop_index(op.f('ix_school_postcode'), table_name='school')
    op.drop_index(op.f('ix_school_patio_separado_infantil'), table_name='school')
    op.drop_index(op.f('ix_school_optionality_third_language'), table_name='school')
    op.drop_index(op.f('ix_school_optionality_second_language'), table_name='school')
    op.drop_index(op.f('ix_school_optionality_fourth_language'), table_name='school')
    op.drop_index(op.f('ix_school_optionality_first_language'), table_name='school')
    op.drop_index(op.f('ix_school_nurse_price'), table_name='school')
    op.drop_index(op.f('ix_school_nurse'), table_name='school')
    op.drop_index(op.f('ix_school_number_pupils'), table_name='school')
    op.drop_index(op.f('ix_school_name'), table_name='school')
    op.drop_index(op.f('ix_school_location_description'), table_name='school')
    op.drop_index(op.f('ix_school_lng'), table_name='school')
    op.drop_index(op.f('ix_school_library'), table_name='school')
    op.drop_index(op.f('ix_school_lat'), table_name='school')
    op.drop_index(op.f('ix_school_infantil_type'), table_name='school')
    op.drop_index(op.f('ix_school_infantil_primer_ciclo_type'), table_name='school')
    op.drop_index(op.f('ix_school_infantil_primer_ciclo'), table_name='school')
    op.drop_index(op.f('ix_school_infantil'), table_name='school')
    op.drop_index(op.f('ix_school_in_house_kitchen'), table_name='school')
    op.drop_index(op.f('ix_school_horario_ampliado_price'), table_name='school')
    op.drop_index(op.f('ix_school_horario_ampliado_morning'), table_name='school')
    op.drop_index(op.f('ix_school_horario_ampliado_afternoon'), table_name='school')
    op.drop_index(op.f('ix_school_horario_ampliado'), table_name='school')
    op.drop_index(op.f('ix_school_headteacher_title'), table_name='school')
    op.drop_index(op.f('ix_school_headteacher'), table_name='school')
    op.drop_index(op.f('ix_school_fourth_language'), table_name='school')
    op.drop_index(op.f('ix_school_formación_profesional_type'), table_name='school')
    op.drop_index(op.f('ix_school_formación_profesional'), table_name='school')
    op.drop_index(op.f('ix_school_first_language'), table_name='school')
    op.drop_index(op.f('ix_school_facilities_information'), table_name='school')
    op.drop_index(op.f('ix_school_extracurricular_activities_price_upto'), table_name='school')
    op.drop_index(op.f('ix_school_extracurricular_activities_price_from'), table_name='school')
    op.drop_index(op.f('ix_school_extracurricular_activities_list'), table_name='school')
    op.drop_index(op.f('ix_school_extracurricular_activities'), table_name='school')
    op.drop_index(op.f('ix_school_email'), table_name='school')
    op.drop_index(op.f('ix_school_director_message'), table_name='school')
    op.drop_index(op.f('ix_school_description_third_language'), table_name='school')
    op.drop_index(op.f('ix_school_description_secundaria'), table_name='school')
    op.drop_index(op.f('ix_school_description_second_language'), table_name='school')
    op.drop_index(op.f('ix_school_description_primaria'), table_name='school')
    op.drop_index(op.f('ix_school_description_infantil_primer_ciclo'), table_name='school')
    op.drop_index(op.f('ix_school_description_infantil'), table_name='school')
    op.drop_index(op.f('ix_school_description_fourth_language'), table_name='school')
    op.drop_index(op.f('ix_school_description_formación_profesional'), table_name='school')
    op.drop_index(op.f('ix_school_description_first_language'), table_name='school')
    op.drop_index(op.f('ix_school_description_bachillerato'), table_name='school')
    op.drop_index(op.f('ix_school_code_number'), table_name='school')
    op.drop_index(op.f('ix_school_city'), table_name='school')
    op.drop_index(op.f('ix_school_canteen_price'), table_name='school')
    op.drop_index(op.f('ix_school_canteen'), table_name='school')
    op.drop_index(op.f('ix_school_bulletpoint_specialities'), table_name='school')
    op.drop_index(op.f('ix_school_bulletpoint_presentation'), table_name='school')
    op.drop_index(op.f('ix_school_bulletpoint_methods_and_priorities'), table_name='school')
    op.drop_index(op.f('ix_school_bilingual'), table_name='school')
    op.drop_index(op.f('ix_school_bachillerato_type'), table_name='school')
    op.drop_index(op.f('ix_school_bachillerato'), table_name='school')
    op.drop_index(op.f('ix_school_address'), table_name='school')
    op.drop_table('school')
    # ### end Alembic commands ###
