"""extracurriculars

Revision ID: 4d7b083861ef
Revises: 8b0abed87bc3
Create Date: 2020-11-20 17:16:16.434592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d7b083861ef'
down_revision = '8b0abed87bc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extracurricular',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracurricular_activity'), 'extracurricular', ['activity'], unique=False)
    op.create_table('school_extracurricular_activities',
    sa.Column('extracurricular_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['extracurricular_id'], ['extracurricular.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school_extracurricular_activities')
    op.drop_index(op.f('ix_extracurricular_activity'), table_name='extracurricular')
    op.drop_table('extracurricular')
    # ### end Alembic commands ###
