"""1

Revision ID: 5eec5334da45
Revises: d82d14fec572
Create Date: 2020-09-13 15:40:53.443596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eec5334da45'
down_revision = 'd82d14fec572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('test', sa.VARCHAR(length=240), nullable=True))
    # ### end Alembic commands ###
