"""empty message

Revision ID: 6297e01faa49
Revises: 143d7c783b7a
Create Date: 2020-11-03 23:15:50.867285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6297e01faa49'
down_revision = '143d7c783b7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('monolingual', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_school_monolingual'), 'school', ['monolingual'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_monolingual'), table_name='school')
    op.drop_column('school', 'monolingual')
    # ### end Alembic commands ###
