"""test3

Revision ID: 722043cdd426
Revises: 9f8e872833e5
Create Date: 2020-09-13 14:07:06.682756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722043cdd426'
down_revision = '9f8e872833e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_school_test'), 'school', ['test'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_test'), table_name='school')
    # ### end Alembic commands ###
