"""empty message

Revision ID: 8b0abed87bc3
Revises: 6cab15eac6c4
Create Date: 2020-11-12 20:57:06.910764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0abed87bc3'
down_revision = '6cab15eac6c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_sports_facilities',
    sa.Column('sports_facility_id', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['sports_facility_id'], ['sports_facilities.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school_sports_facilities')
    # ### end Alembic commands ###
