"""test_part2

Revision ID: 9f8e872833e5
Revises: 08088b5bc461
Create Date: 2020-09-13 13:59:53.215207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8e872833e5'
down_revision = '08088b5bc461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_school_test', table_name='school')
    op.drop_column('school', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('test', sa.VARCHAR(length=240), nullable=True))
    op.create_index('ix_school_test', 'school', ['test'], unique=False)
    # ### end Alembic commands ###
