"""zone and borough

Revision ID: d82d14fec572
Revises: c219a085bbe4
Create Date: 2020-09-13 15:28:55.092617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd82d14fec572'
down_revision = 'c219a085bbe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('borough', sa.String(length=32), nullable=True))
    op.add_column('school', sa.Column('zone', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_school_borough'), 'school', ['borough'], unique=False)
    op.create_index(op.f('ix_school_zone'), 'school', ['zone'], unique=False)
    op.drop_column('school', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('test', sa.VARCHAR(length=240), nullable=True))
    op.drop_index(op.f('ix_school_zone'), table_name='school')
    op.drop_index(op.f('ix_school_borough'), table_name='school')
    op.drop_column('school', 'zone')
    op.drop_column('school', 'borough')
    # ### end Alembic commands ###
