"""extracurriculars offered

Revision ID: dcbb4cfbef86
Revises: 4d7b083861ef
Create Date: 2020-11-20 17:56:02.853106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcbb4cfbef86'
down_revision = '4d7b083861ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('extracurricular_activities_offered', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_school_extracurricular_activities_offered'), 'school', ['extracurricular_activities_offered'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_extracurricular_activities_offered'), table_name='school')
    op.drop_column('school', 'extracurricular_activities_offered')
    # ### end Alembic commands ###
